name: HideAndSeek
version: '${version}'
main: matanku.kakurembo.HideAndSeek
api-version: 1.21
author: a
commands:
  cosmetics:
  hideandseek:
    aliases: [has]
permissions:
  admin:
    description: HI
  gameadmin:
    description: HI
depend:
  - api
  - DecentHolograms
  - PlaceholderAPI