name: HideAndSeek
version: '${version}'
main: matanku.kakurembo.HideAndSeek
api-version: 1.21
author: a
commands:
  setbuilder:
    permission: op
    permission-message: §cYou don't have permissions to run that command!
  settrackerenabled:
    permission: op
    permission-message: §cYou don't have permissions to run that command!
  countdown:
    permission: aiueo
    permission-message: §cYou don't have permissions to run that command!
  disguiseselect:
  roleselect:
  party:
    aliases: [p]
  chat:
    aliases: [ch]
  setlobby:
    permission-message: §cYou don't have permissions to run that command!
    permission: op
  settings:
    permission: aiueo
    permission-message: §cYou don't have permissions to run that command!
  stopdisguise:
    permission: op
    permission-message: §cYou don't have permissions to run that command!
  stoptask:
    permission: op
    permission-message: §cYou don't have permissions to run that command!
permissions:
  aiueo:
    description: HI
depend:
  - api
  - DecentHolograms