package matanku.kakurembo.util;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum CC {

	//Minecraft Default Color
	BLACK("black"),
	DARK_BLUE("dark_blue"),
	DARK_GREEN("dark_green"),
	DARK_AQUA("dark_aqua"),
	DARK_RED("dark_red"),
	DARK_PURPLE("dark_purple"),
	GOLD("gold"),
	GRAY("gray"),
	DARK_GRAY("dark_gray"),
	BLUE("blue"),
	GREEN("green"),
	AQUA("aqua"),
	RED("red"),
	LIGHT_PURPLE("light_purple"),
	YELLOW("yellow"),
	WHITE("white"),
	MAGIC("obfuscated"),
	BOLD("bold"),
	UN_BOLD("!bold"),
	STRIKETHROUGH("strikethrough"),
	UNDERLINE("underlined"),
	ITALIC("italic"),
	RESET("reset"),

	//Custom color using hex code
	ORANGE_RED("#FF4500"),
	ORANGE("#FFA500"),
	CHARTREUSE("#7FFF00"),
	LIME_GREEN("#00FF00"),
	SPRING_GREEN("#00FF7F"),
	SEA_GREEN("#2E8B57"),
	CYAN("#00BFFF"),
	SKY_BLUE("#87CEEB"),
	DODGER_BLUE("#1E90FF"),
	NAVY_BLUE("#000080"),
	INDIGO("#4B0082"),
	PURPLE("#800080"),
	VIOLET("#EE82EE"),
	MAGENTA("#FF00FF"),
	PINK("#FFC0CB"),
	LIGHT_PINK("#FFB6C1"),
	PEACH_PUFF("#FFDAB9"),
	SALMON("#FA8072"),
	CORAL("#FF7F50"),
	TOMATO("#FF6347"),
	DARK_ORANGE("#FF8C00"),
	ORANGE_PEEL("#FF9F00"),
	GOLDENROD("#DAA520"),
	KHAKI("#F0E68C"),
	LEMON_CHIFFON("#FFFACD"),
	PALE_YELLOW("#FFFF99"),
	YELLOW_GREEN("#9ACD32"),
	OLIVE_GREEN("#556B2F"),
	TEAL("#008080"),
	TURQUOISE("#40E0D0"),
	LIGHT_BLUE("#ADD8E6"),
	POWDER_BLUE("#B0E0E6"),
	STEEL_BLUE("#4682B4"),
	ROYAL_BLUE("#4169E1"),
	MEDIUM_BLUE("#0000CD"),
	SLATE_BLUE("#6A5ACD"),
	LAVENDER("#E6E6FA"),
	THISTLE("#D8BFD8"),
	PLUM("#DDA0DD"),
	ORCHID("#DA70D6"),
	HOT_PINK("#FF69B4"),
	DEEP_PINK("#FF1493"),
	INDIAN_RED("#CD5C5C"),
	CRIMSON("#DC143C"),
	FIREBRICK("#B22222"),
	MAROON("#800000"),
	BROWN("#A52A2A"),
	SIENNA("#A0522D"),
	PERU("#CD853F"),
	SANDY_BROWN("#F4A460"),
	WHEAT("#F5DEB3"),
	BEIGE("#F5F5DC"),
	CORNSILK("#FFF8DC"),
	LEMON("#FFF700"),
	LIGHT_GOLD("#FFEC8B"),
	GOLDEN("#FFDF00"),
	YELLOW_ORANGE("#FFC200"),
	TANGERINE("#FF8300"),
	CARROT("#FF7F00"),
	BURNISHED_BROWN("#8A3324"),
	MAHOGANY("#C04000"),
	CHOCOLATE("#D2691E"),
	SADDLE_BROWN("#8B4513"),
	DARK_BROWN("#5C4033"),
	BRONZE("#CD7F32"),
	COPPER("#B87333"),
	BRASS("#B5A642"),
	GOLDEN_YELLOW("#FFDF00"),
	SUN_YELLOW("#FFE400"),
	MELLOW_YELLOW("#F8DE7E"),
	BANANA("#E3CF57"),
	BUFF("#F0DC82"),
	BLONDE("#FAF0BE"),
	SAND("#C2B280"),
	RAFFIA("#EADAC2"),
	DESERT("#C19A6B"),
	;

	private final String color;

	@Override
	public String toString() {
		return "<" + color + ">";
	}
}
