name: Kenchiku
version: '${version}'
main: matanku.kakurembo.kenchiku.Kenchiku
api-version: 1.21
author: matanku, goodestenglish
commands:
  server:
    aliases: [s,world]
  lobby:
    aliases: [l]
  spec:
    aliases: [spectate]
  exit:
  tps:
  sine:
  ping:
depend:
  - api
  - DecentHolograms